version: '3'

services:
  # QUIC client
  client:
    build:
      context: nodes/client
    entrypoint: /root/entrypoint.bash "client" ${DOMAIN1_ROUTER_ADDR} ${DOMAIN2_SUBNET}
    container_name: client
    networks:
      domain1:
        ipv4_address: ${DOMAIN1_CLIENT_ADDR}
      datacollection:
    ports:
      - "8081:8080"
    extra_hosts:
      - "server:${DOMAIN2_SERVER_ADDR}" 
      - "router:${DOMAIN1_ROUTER_ADDR}"
    volumes:
      - ./volumes:/root/share
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # QUIC server
  server:
    build:
      context: nodes/server
    entrypoint: /root/entrypoint.bash "server" ${DOMAIN2_ROUTER_ADDR} ${DOMAIN1_SUBNET}
    container_name: server
    networks:
      domain2:
        ipv4_address: ${DOMAIN2_SERVER_ADDR}
      datacollection:
    ports:
      - "8082:8080"
    extra_hosts:
      - "client:${DOMAIN1_CLIENT_ADDR}" 
      - "router:${DOMAIN2_ROUTER_ADDR}"
    volumes:
      - ./volumes:/root/share
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # router
  router:
    build:
      context: nodes/router
    entrypoint: /root/entrypoint.bash "router"
    container_name: router
    networks:
      domain2:
        ipv4_address: ${DOMAIN2_ROUTER_ADDR}
      domain1:
        ipv4_address: ${DOMAIN1_ROUTER_ADDR}
      datacollection:
    ports:
      - "8083:8080"
    extra_hosts:
      - "client:${DOMAIN1_CLIENT_ADDR}" 
      - "server:${DOMAIN2_SERVER_ADDR}"
    volumes:
      - ./volumes:/root/share
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # storage/graphing infra
  # Telegraf
  telegraf:
    image: telegraf:1.4.0
    container_name: telegraf
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      datacollection:
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # InfluxDB
  influxdb:
    image: influxdb:1.3.5
    container_name: influxdb
    networks:
      datacollection:
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  # Chronograf
  chronograf:
    image: chronograf:1.3.8
    container_name: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
    networks:
      datacollection:
    ports:
      - "8888:8888"
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb:1.3.5
    container_name: influxdb-cli
    entrypoint:
      - influx
      - -host
      - influxdb
    networks:
      datacollection:

networks:
  domain1:
    ipam:
      config:
        - subnet: ${DOMAIN1_SUBNET}
  domain2:
    ipam:
      config:
        - subnet: ${DOMAIN2_SUBNET}
  datacollection:


# vim: ai ts=2 sw=2 et sts=2 ft=yaml
